### ISSUE TITLE
better integration with additional mission types haven siege

### ISSUE THREAD

**Issue by adamzl** [MalucoMarinero/XCOM2GuerillaWarfare#37]
the haven siege mission from the additional mission types mod is an alternative retaliation mission. my assertion is it is even harder than a standard retaliation because you are constantly attacked by advent instead of chasing them to stop killing civies.

the fantastic logic of guerrilla war that you can pull out and fail a mission **does not work** for this mission type though, **you cannot call the skyranger until the waves stop spawning**. there are other mission types from the mod that make more sense and are easier where the skyranger is purposely removed for a set number of turns and that seems okay because you are given time to setup and initiate it.

if possible i would suggest changing the haven siege to allow a retreat and failure.

**Comment by MalucoMarinero** [comment]
that's something you'll need to bring up with RealityMachina, deactivating evac is built into the mission, GW doesn't actually change anything about it.
